package main

import (
	"flag"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	var flags flag.FlagSet

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	filename := file.GeneratedFilenamePrefix + ".order.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-order. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, message := range file.Messages {
		generateMessage(g, message)
	}

	for _, service := range file.Services {
		generateService(g, service)
	}

	return nil
}

func generateMessage(g *protogen.GeneratedFile, message *protogen.Message) {
	g.P("// ", message.GoIdent.GoName, " helper methods")
	g.P()

	// Generate ToProto method
	g.P("func (m *", message.GoIdent.GoName, ") ToProto() *", message.GoIdent.GoName, " {")
	g.P("  if m == nil {")
	g.P("    return nil")
	g.P("  }")
	g.P("  return m")
	g.P("}")
	g.P()

	// Generate Validate method
	g.P("func (m *", message.GoIdent.GoName, ") Validate() error {")
	g.P("  if m == nil {")
	g.P("    return nil")
	g.P("  }")
	g.P("  return nil")
	g.P("}")
	g.P()
}

func generateService(g *protogen.GeneratedFile, service *protogen.Service) {
	g.P("// ", service.GoName, "Server interface")
	g.P()

	// Generate server interface
	g.P("type ", service.GoName, "Server interface {")
	for _, method := range service.Methods {
		g.P("  ", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ") (*", method.Output.GoIdent.GoName, ", error)")
	}
	g.P("}")
	g.P()

	// Generate client interface
	g.P("type ", service.GoName, "Client interface {")
	for _, method := range service.Methods {
		g.P("  ", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent.GoName, ", opts ...grpc.CallOption) (*", method.Output.GoIdent.GoName, ", error)")
	}
	g.P("}")
	g.P()
}
